### ISSUE TITLE
Implement an option to disable a user

### ISSUE THREAD

**Issue by jkirk** [jkirk/ansible-role-user#1]
If `disable: true` run the following tasks:

```yaml
---
- name: Disable user account for {{ item }}
  user:
    name: "{{ item }}"
    password_lock: true
    shell: "/usr/sbin/nologin"
- name: Remove authorized_keys file
  file:
    path: "/home/{{ item }}/.ssh/authorized_keys"
    state: absent
- name: Remove authorized_keys2 file
  file:
    path: "/home/{{ item }}/.ssh/authorized_keys2"
    state: absent
```
